exports.CONNECT_TO_STREAM = 'CONNECT_TO_STREAM';
exports.CONNECTED = 'CONNECTED';
exports.SEND_COMMENTS = 'SEND_COMMENTS';
exports.APPROVE_COMMENT = 'APPROVE_COMMENT';
exports.DISAPPROVE_COMMENT = 'DISAPPROVE_COMMENT';
